### PR TITLE
Add compatibility for gatesgarth yocto

### PR DESCRIPTION
**Pull request by ubfx**
Very useful for yocto builds

### CODE REVIEW

**Comment by mhatle** [comment]
2020.3 is not campatible with gatesgarth.  It is only compatible w/ Zeus.

If you want gatesgarth please use the gatesgarth branch.  If there is something missing from there that is in 2020.3, please let me know, it's easy for me to forward port.

**Comment by ubfx** [comment]
Out of curiosity, since I'm still trying to understand the yocto project and everything involved:
the gatesgarth branch uses the 2020.2 xsct and is compatible to gatesgarth (which is newer than zeus)
the 2020.3 branch uses the 2020.3 xsct and is compatible to zeus

Would you be so kind to explain why this was chosen this way? I would think the newest tools would be compatible to the newest yocto release

**Comment by ubfx** [comment]
I just tested the gatesgarth branch. With the xsct.2020.2 tools it uses, my device won't boot. Something seems to be wrong there. If I use the 2020.3 but add gatesgarth compatibility, everything works. Would it be possible to port the 2020.3 xsct tools to gatesgarth?

**Comment by mhatle** [comment]
@ubfx Can you email me at mark.hatle@xilinx.com, I'd like to know more about your configuration.

The 2020.3 toolset is specific to versal platforms, which is why gatesgarth wasn't updated to 2020.3 when it was released.  If I can understand your configuration I can formulate a strategy to make sure the right xsct can be selected.

**Pull request closed without merging**
